export type Spot = { name: string; city: string; lat: number; lon: number; };
export const spots: Spot[] = [
    { "name": "Sainte-Barbe", "city": "Plouharnel", "lat": 47.594, "lon": -3.135 },
    { "name": "Kerhillio", "city": "Erdeven", "lat": 47.631, "lon": -3.205 },
    { "name": "La Torche", "city": "Plomeur", "lat": 47.839, "lon": -4.355 },
    { "name": "Pors Carn", "city": "Penmarch", "lat": 47.812, "lon": -4.379 },
    { "name": "Tronoën", "city": "Saint-Jean-Trolimon", "lat": 47.846, "lon": -4.328 },
    { "name": "Penhors", "city": "Pouldreuzic", "lat": 47.989, "lon": -4.431 },
    { "name": "Goulien", "city": "Cap Sizun", "lat": 48.058, "lon": -4.612 },
    { "name": "Lostmarc'h", "city": "Crozon", "lat": 48.219, "lon": -4.524 },
    { "name": "La Palue", "city": "Crozon", "lat": 48.219, "lon": -4.531 },
    { "name": "Kerloch", "city": "Crozon", "lat": 48.260, "lon": -4.593 },
    { "name": "Le Minou", "city": "Plouzané", "lat": 48.360, "lon": -4.617 },
    { "name": "Blancs Sablons", "city": "Le Conquet", "lat": 48.364, "lon": -4.770 },
    { "name": "Fort Bloqué", "city": "Ploemeur", "lat": 47.723, "lon": -3.493 },
    { "name": "Port Blanc", "city": "Quiberon", "lat": 47.508, "lon": -3.138 },
    { "name": "Port Bara (Côte Sauvage)", "city": "Quiberon", "lat": 47.486, "lon": -3.192 },
    { "name": "La Sauzaie", "city": "Brétignolles-sur-Mer", "lat": 46.640, "lon": -1.861 },
    { "name": "Les Dunes", "city": "Brétignolles-sur-Mer", "lat": 46.659, "lon": -1.885 },
    { "name": "Bud Bud", "city": "Longeville-sur-Mer", "lat": 46.395, "lon": -1.509 },
    { "name": "Les Conches", "city": "Longeville-sur-Mer", "lat": 46.408, "lon": -1.505 },
    { "name": "La Terrière", "city": "La Tranche-sur-Mer", "lat": 46.340, "lon": -1.468 },
    { "name": "Tanchet", "city": "Les Sables-d’Olonne", "lat": 46.485, "lon": -1.778 },
    { "name": "Sauveterre", "city": "Olonne-sur-Mer", "lat": 46.559, "lon": -1.840 },
    { "name": "Saint-Gilles La Garenne", "city": "Saint-Gilles-Croix-de-Vie", "lat": 46.697, "lon": -1.940 },
    { "name": "Vert-Bois", "city": "Île d’Oléron", "lat": 45.890, "lon": -1.273 },
    { "name": "Les Huttes", "city": "Île d’Oléron", "lat": 45.994, "lon": -1.395 },
    { "name": "Côte Sauvage", "city": "La Tremblade", "lat": 45.737, "lon": -1.222 },
    { "name": "Lacanau Océan", "city": "Lacanau", "lat": 44.999, "lon": -1.205 },
    { "name": "Le Porge", "city": "Le Porge", "lat": 45.077, "lon": -1.222 },
    { "name": "Carcans", "city": "Carcans-Plage", "lat": 45.091, "lon": -1.155 },
    { "name": "Hourtin", "city": "Hourtin-Plage", "lat": 45.170, "lon": -1.170 },
    { "name": "Mimizan", "city": "Mimizan-Plage", "lat": 44.215, "lon": -1.299 },
    { "name": "Contis", "city": "Contis-Plage", "lat": 44.074, "lon": -1.332 },
    { "name": "Cap de l’Homy", "city": "Lit-et-Mixe", "lat": 43.997, "lon": -1.365 },
    { "name": "Saint-Girons", "city": "Saint-Girons-Plage", "lat": 43.930, "lon": -1.380 },
    { "name": "Moliets", "city": "Moliets-Plage", "lat": 43.860, "lon": -1.401 },
    { "name": "Messanges", "city": "Messanges-Plage", "lat": 43.819, "lon": -1.431 },
    { "name": "Vieux-Boucau", "city": "Vieux-Boucau", "lat": 43.792, "lon": -1.438 },
    { "name": "Seignosse Le Penon", "city": "Seignosse", "lat": 43.691, "lon": -1.440 },
    { "name": "Hossegor La Gravière", "city": "Soorts-Hossegor", "lat": 43.664, "lon": -1.447 },
    { "name": "Capbreton Santocha", "city": "Capbreton", "lat": 43.647, "lon": -1.442 },
    { "name": "Anglet Les Cavaliers", "city": "Anglet", "lat": 43.511, "lon": -1.531 },
    { "name": "Biarritz Côte des Basques", "city": "Biarritz", "lat": 43.475, "lon": -1.569 },
    { "name": "Bidart Centre", "city": "Bidart", "lat": 43.440, "lon": -1.591 },
    { "name": "Guéthary Parlementia", "city": "Guéthary", "lat": 43.424, "lon": -1.611 },
    { "name": "Hendaye Plage", "city": "Hendaye", "lat": 43.372, "lon": -1.778 },
    { "name": "Siouville-Hague", "city": "Siouville", "lat": 49.563, "lon": -1.822 },
    { "name": "Le Rozel", "city": "Le Rozel", "lat": 49.480, "lon": -1.832 },
    { "name": "Wimereux", "city": "Wimereux", "lat": 50.772, "lon": 1.612 },
    { "name": "Wissant", "city": "Wissant", "lat": 50.888, "lon": 1.658 },
    { "name": "Six-Fours Brutal Beach", "city": "Six-Fours-les-Plages", "lat": 43.078, "lon": 5.807 }
];
export const slugify = (s: string) =>
    s.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
export const spotSlug = (spot: Spot) => `${slugify(spot.name)}-${slugify(spot.city)}`;
export const findBySlug = (slug: string) => spots.find(s => spotSlug(s) === slug);
